# Generated by Django 3.2 on 2021-04-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('outros', 'outros')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CellphonePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=10)),
                ('premium_data', models.CharField(max_length=50)),
                ('talk', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=50)),
                ('lines', models.CharField(choices=[('1 linha', '1 linha'), ('2 linhas', '2 linhas'), ('3 linhas', '3 linhas')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telecom_system.client')),
            ],
        ),
    ]
