# Generated by Django 3.2 on 2021-05-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecom_system', '0002_auto_20210430_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellphoneplan',
            name='talk',
        ),
        migrations.RemoveField(
            model_name='cellphoneplan',
            name='text',
        ),
    ]
