# Generated by Django 3.2 on 2021-05-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecom_system', '0003_auto_20210502_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CellphonePlan',
        ),
    ]
